name: GitHub Actions CI/CD Comics VUE FRONT-END

on:
  push:
    branches: [main]
    
jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest
   
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build and test
        run:
          npm install
          npm test
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:8080'
          config: baseUrl=https://localhost:8080
        env:
          privateKey: ${{ secrets.privateKey }}
          publicKey: ${{ secrets.publicKey }}


  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Add remote origin to Heroku
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      
      - name: Deploy code to heroku
        run: git push --force heroku main